### ISSUE TITLE
1.2.0: TODO

### ISSUE THREAD

**Issue by kotajacob** [kotajacob/wal_steam#46]
#- [x] Add config file
- [x] Testing on windows and finding issues.
- [x] Better detection of missing files.
- [x] Download the config file if missing.
- [x] Command line option to download new config.json file and cache.
- [x] Command line option to specify custom steam install.
- [x] Alpha color information, re-implementation in the config.json file.
- [x] Switch to argparse

**Comment by kotajacob** [comment]
Now starting testing for release 1.2.0!

- [ ] Arch Linux
- [ ] Ubuntu Linux (16.04)
- [ ] Fedora Linux (26)
- [ ] Debian Linux (9)
- [ ] Windows (10)
